apiVersion: xcluster.ovsandbox.com/v1alpha1
kind: cls
metadata:
  name: ovsandbox-eks
  namespace: teams
spec:
  resourceConfig:
    deletionPolicy: Delete
    providerConfigName: aws-provider-config
    k8sproviderConfigName: kubernetes-provider
    region: eu-west-1
    tags:
      - key: env
        value: test
      - key: ovsandbox
        value: crossplane
    objectTags:
      key: env
  parameters:
    #EKS Input parameters
    version: "1.27"
    endpointPrivateAccess: false
    endpointPublicAccess: true
    subnetIds: # Update your private subnet ids
      - "subnet-02ce2c72399b74cc3"
      - "subnet-06eaf2e689460fb60"
      - "subnet-0d2c80f584b450205"
    secretName: xplane-ovsandbox-eks-cluster
  managedNodeGroups:
    minSize: 1
    desiredSize: 1
    maxSize: 2
    capacityType: SPOT
    instanceTypes:
      - m6a.large
      - m5a.large
      - m5.large
  writeConnectionSecretToRef:
    name: xplane-eks-cluster
