apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams-claims
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: teams
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/ovaleanu/eks-argo-crossplane.git"
    targetRevision: HEAD
    path: gitops-repositories/claims
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
