apiVersion: v1
kind: Secret
metadata:
  name: eks-argo-crossplane.git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ovaleanu/eks-argo-crossplane.git
