# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#----------------------------------------------------------------------------------
# This example resource creates the following resources
#     1. EKS Cluster with VPC
#     2. EKS Cluster IAM Role
#     3. Attaches EKS Cluster Policies to the IAM Role
#     4. EKS Managed Node group
#     5. IAM Role for EKS Managed Node group
#     6. Attaches EKS Managed Node Policies to the IAM Role
#     7. Update the aws-auth config map to allow admin access (defaults to Admin role)
#     8. Installs Cluster Auto Scaler with proper roles.
#----------------------------------------------------------------------------------
---
apiVersion: cluster.ovsandbox.com/v1alpha1
kind: amazonEks
metadata:
  name: xplane-ovsandbox-eks
  namespace: teams
spec:
  compositionSelector:
    matchLabels:
      ovsandbox.com/provider: aws
      ovsandbox.com/environment: dev
      ovsandbox.com/subnet-selection: id
      service: eks
  resourceConfig:
    providerConfigName: aws-provider-config
    region: eu-west-1
  parameters:
    # This field tells which role should have admin access to this cluster.
    adminRole: Admin
    version: "1.27"
    endpointPrivateAccess: false
    endpointPublicAccess: true
    subnetIds: # Update your subnet ids
      - "subnet-02d759aeec4755213"
      - "subnet-042cd9e0eefcd896f"
      - "subnet-0ed072bc4676ff3cc"
  managedNodeGroups:
    minSize: 1
    desiredSize: 2
    maxSize: 2
    capacityType: SPOT
  writeConnectionSecretToRef:
    name: xplane-eks-cluster
